### POST POSTS
POST http://localhost:5000/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiZDIxN2E4OTljODJjZjUwN2YzN2Y0In0sImlhdCI6MTY5MDE3MzA1OCwiZXhwIjoxNjkwMTc2NjU4fQ.K4MT0o4HV4RCoSt5fuRbIoe4aTwbejmgDir4lWJ7Ok4
Content-Type: application/json

{
  "title": "Sherozbek", 
  "description": "Baxtiyorov", 
  "image": "sherozbek1111@gmail.com",
  "web_link": "1234"
}


### GET POSTS
GET http://localhost:5000/posts
Content-Type: application/json


### SHOW POSTS
GET http://localhost:5000/posts/64bd08d8c9847c261b2cf278
Content-Type: application/json


### GET USERS POSTS
GET http://localhost:5000/posts/users/64bd217a899c82cf507f37f4
Content-Type: application/json



### USERS LIKE POSTS
PUT http://localhost:5000/users/like/posts/64bd08d8c9847c261b2cf278
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiZDIxN2E4OTljODJjZjUwN2YzN2Y0In0sImlhdCI6MTY5MDE3MzA1OCwiZXhwIjoxNjkwMTc2NjU4fQ.K4MT0o4HV4RCoSt5fuRbIoe4aTwbejmgDir4lWJ7Ok4
Content-Type: application/json