### POST POSTS
POST http://localhost:5000/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiZjk1YTc0YjJlZWI2NDM5ZDRiNDlhIn0sImlhdCI6MTY5MDI3NzI5OSwiZXhwIjoxNjkwMjgwODk5fQ.HS9aJcD4RzdJH3F7NJ3Xbbw2wocxPO_KQ3Tn1HzIAC0
Content-Type: application/json

{
  "title": "Sherozbek", 
  "description": "Baxtiyorov", 
  "image": "sherozbek1111@gmail.com",
  "web_link": "1234"
}


### GET POSTS
GET http://localhost:5000/posts
Content-Type: application/json


### SHOW POSTS
GET http://localhost:5000/posts/64be07ddd20c9bc5f8b4c67c
Content-Type: application/json


### GET USERS POSTS
GET http://localhost:5000/posts/users/64be07ddd20c9bc5f8b4c67c
Content-Type: application/json



### USERS LIKE POSTS
PUT http://localhost:5000/users/like/posts/64bf964b4b2eeb6439d4b49d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiZjljNjY3YTA1MGUxMjJkY2VmODFkIn0sImlhdCI6MTY5MDM3MTg0NywiZXhwIjoxNjkwMzc1NDQ3fQ.4NV-Lu9GXtIKeO9KMPNY0K93hyIBei-79PB9c-HG-1k
Content-Type: application/json