### REGISTER USER
POST http://localhost:5000/register
Content-Type: application/json

{
  "first_name": "Sherozbek", 
  "last_name": "Baxtiyorov", 
  "email": "sherozbek1111@gmail.com",
  "username": "sheroz",
  "password": "1234"
}


### LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "sheroz",
  "password": "1234"
}